apiVersion: v1
kind: ServiceAccount
metadata:
  name: dpp-worker-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::399078540634:role/dpp-worker-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dpp-api-sa
